### ISSUE TITLE
xfrrat and nxfrat should be stored as integers

### ISSUE THREAD

**Issue by blue442** [lanl-ansi/grg-pssedata#14]
Hey there -

Feedback from pnnl on our case submissions for the go competition insists that the xfrrat and nxfrat values on the case object should be stored as integers as opposed to floats. I believe these objects' datatypes are only referenced once in your code base: 

https://github.com/lanl-ansi/grg-pssedata/blob/f32e0d6346641131fa015dfbcdd8c70a42b274e6/grg_pssedata/struct.py#L67
https://github.com/lanl-ansi/grg-pssedata/blob/f32e0d6346641131fa015dfbcdd8c70a42b274e6/grg_pssedata/struct.py#L68 

and was wondering if you could submit a change to fix this.

We're using the grg-pssedata package to provide an in-memory data structure for storage of the data from the raw file - I could fork the repo and create our own, but it's a small fix, would save me some headache, and I figured you'd want it fixed anyway. Apparently psse will fail on import with these values represented as a float. The psse documentation is unclear on this point (and in fact I interpreted it as a float as well) and this data isn't used in the competition, but a fix would be greatly appreciated.

Thanks!

-Steve

**Comment by ccoffrin** [comment]
Sounds reasonable, who made this claim "psse will fail on import with these values represented as a float"?  It is somewhat shocking given how vague the docs are on this point.

**Comment by pseudocubic** [comment]
You may use this branch to test your issue is resolved:

https://github.com/lanl-ansi/grg-pssedata/tree/fix/case-identification-dtypes
